//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA_MDM_MvcApp_2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Authors()
        {
            this.MdmBlogDetails = new HashSet<MdmBlogDetails>();
            this.MisakBlogDetails = new HashSet<MisakBlogDetails>();
        }
    
        public int AuthorId { get; set; }
        public string NameSurname { get; set; }
        public string ImageURL { get; set; }
        public string FacebookURL { get; set; }
        public string YoutubeURL { get; set; }
        public string TwitterURL { get; set; }
        public string InstagramURL { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public int AuthorCategoryId { get; set; }
    
        public virtual AuthorCategories AuthorCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MdmBlogDetails> MdmBlogDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MisakBlogDetails> MisakBlogDetails { get; set; }
    }
}
