//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA_MDM_MvcApp_2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int ContactId { get; set; }
        public string ContactAdress { get; set; }
        public string ContactNumber { get; set; }
        public string TwitterURL { get; set; }
        public string InstagramURL { get; set; }
        public string FacebookURL { get; set; }
        public string YoutubeURL { get; set; }
        public string LinkedinURL { get; set; }
        public bool IsActive { get; set; }
    }
}
