//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA_MDM_MvcApp_2021.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MDMContext : DbContext
    {
        public MDMContext()
            : base("name=MDMContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abouts> Abouts { get; set; }
        public virtual DbSet<Announcements> Announcements { get; set; }
        public virtual DbSet<AuthorCategories> AuthorCategories { get; set; }
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<MdmBlogDetails> MdmBlogDetails { get; set; }
        public virtual DbSet<MdmBlogs> MdmBlogs { get; set; }
        public virtual DbSet<MdmComments> MdmComments { get; set; }
        public virtual DbSet<MisakBlogDetails> MisakBlogDetails { get; set; }
        public virtual DbSet<MisakBlogs> MisakBlogs { get; set; }
        public virtual DbSet<MisakCategories> MisakCategories { get; set; }
        public virtual DbSet<MisakLocations> MisakLocations { get; set; }
        public virtual DbSet<MisakTags> MisakTags { get; set; }
        public virtual DbSet<MskComments> MskComments { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<MdmCategories> MdmCategories { get; set; }
    }
}
